CREATE TABLE clientes(
ID INT AUTO_INCREMENT,
Nome VARCHAR(100) NOT NULL,
Email VARCHAR(150) UNIQUE NOT NULL,
DataNascimento DATE NOT NULL,
PRIMARY KEY (ID)
);



CREATE TABLE produto(
ID INT AUTO_INCREMENT,
Descricao VARCHAR(100) NOT NULL,
Preco DECIMAL (10,2) NOT NULL,
Stock INT NOT NULL DEFAULT 0,
PRIMARY KEY (ID)
);



CREATE TABLE venda(
ID INT AUTO_INCREMENT,
ClienteID INT NOT NULL,
ProdutoID INT NOT NULL,
DataVenda DATE NOT NULL,
Quantidade INT NOT NULL CHECK (Quantidade>0),
PRIMARY KEY (ID)
);



ALTER TABLE venda
ADD FOREIGN KEY (ClienteID) REFERENCES cliente(ID),
ADD FOREIGN KEY (ProdutoID) REFERENCES produto(ID);